[project]
name = "cmugpt-surface"
revision = "1.0"

[providers]
local = "dotenv://.env"

[profiles.ci.defaults]
required = false

[profiles.default]
OIDC_CLIENT_ID      = { description = "OIDC client ID", required = true, provider = ["local", "vault"] }
OIDC_CLIENT_SECRET  = { description = "OIDC client secret", required = true, provider = ["local", "vault"] }
OIDC_ISSUER_URL     = { description = "OIDC issuer URL", provider = ["local", "vault"]}
OAUTH_RELAY_URL     = { description = "Shared ricochet OAuth relay callback URL", required = false, provider = ["local", "vault"] }
AGENT_API_URL       = { description = "cmugpt-agent base URL", default = "https://api.cmugpt-agent.scottylabs.org", provider = ["local", "vault"] }
AGENT_SHARED_SECRET = { description = "Must match agent's AGENT_SHARED_SECRET", required = false, provider = ["local", "vault"] }
ALLOWED_ORIGINS_REGEX = { description = "Allowed origins", default = ".", provider = ["local, vault"]}

[profiles.prod]

[profiles.staging]

[profiles.preview]

[profiles.dev]

