[project]
name = "cmugpt-surface"
revision = "1.0"

[providers]
local = "dotenv://.env"
vault = "vault://secrets2.scottylabs.org/secret"

[profiles.ci.defaults]
required = false

[profiles.default]
OIDC_CLIENT_ID      = { description = "OIDC client ID", default = "sl-ai-local", required = false, provider =  ["vault"] }
OIDC_CLIENT_SECRET  = { description = "OIDC client secret", required = false, provider = ["vault"] }
OIDC_ISSUER_URL     = { description = "OIDC issuer URL", provider = ["vault"]}
OAUTH_RELAY_URL     = { description = "Shared ricochet OAuth relay callback URL", required = false, provider = ["vault"] }
AGENT_API_URL       = { description = "cmugpt-agent base URL", default = "https://api.cmugpt-agent.scottylabs.org", provider = ["vault"] }
AGENT_SHARED_SECRET = { description = "Must match agent's AGENT_SHARED_SECRET", required = false, provider = ["vault"] }
ALLOWED_ORIGINS_REGEX = { description = "Allowed origins", default = ".", provider = ["vault"]}

[profiles.prod]

[profiles.staging]

[profiles.preview]

[profiles.dev]

[profiles.dev.defaults]
providers = ["vault"]
