[project]
name = "cmugpt-surface"
revision = "1.0"

[profiles.default]
OIDC_CLIENT_ID = { description = "Keycloak OIDC client ID" , required = true}
OIDC_CLIENT_SECRET = { description = "Keycloak OIDC client secret", required = true }
OIDC_ISSUER_URL       = { description = "Keycloak issuer", default = "https://idp.scottylabs.org/realms/scottylabs" }
AGENT_API_URL         = { description = "cmugpt-agent base URL", default = "https://api.cmugpt-agent.scottylabs.org" }
AGENT_SHARED_SECRET   = { description = "Must match agent's AGENT_SHARED_SECRET", required = false }
ADMIN_GROUP           = { description = "Keycloak admin group", required = false }

[profiles.prod]


SERVER_URL            = { description = "Public API URL", default = "https://cmugpt-surface-server-main.scottylabs.net" }
ALLOWED_ORIGINS_REGEX = { description = "Allowed CORS origins", default = "https://cmugpt-surface-web-main.scottylabs.net" }