name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: docker
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Setup Deno
        uses: https://github.com/denoland/setup-deno@v1
        with:
          deno-version: v2.4.2

      - name: Install Playwright
        run: deno run -A npm:@playwright/test install --with-deps chromium

      - name: Check EditorConfig
        env:
          GITHUB_TOKEN: ""
        run: deno run -A npm:@editorconfig-checker/editorconfig-checker --exclude '^LICENSE'

      - name: Generate API Artifacts
        run: deno task generate

      - name: Check Workspace
        run: deno task check

      - name: Build
        run: deno task build

      - name: Test Browser Surface
        run: deno task test:e2e
