import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
});

const LAST_UPDATED = "August 15th, 2026";

interface TermsSectionData {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
  trailing?: string[];
}

const SECTIONS: TermsSectionData[] = [
  {
    heading: "About This Service",
    paragraphs: [
      "Bark is a student-built project developed by ScottyLabs, an " +
      "independent student organization at Carnegie Mellon University. " +
      "Bark is not an official CMU service, and is not endorsed by, " +
      "operated by, or affiliated with the CMU administration.",
    ],
  },
  {
    heading: "No Warranty",
    paragraphs: [
      'Bark is provided "as is" and "as available," with no guarantees ' +
      "of any kind. We make no promises regarding:",
    ],
    bullets: [
      "Accuracy, completeness, or reliability of any responses",
      "Uptime, availability, or continued operation of the service",
      "Fitness for any particular purpose",
    ],
    trailing: [
      "AI-generated responses may be incorrect, outdated, or misleading. " +
      "Do not rely on Bark as a substitute for official CMU resources " +
      "(registrar, academic advisors, course catalogs, etc.) for decisions " +
      "that matter.",
    ],
  },
  {
    heading: "Data Handling",
    paragraphs: [
      "We make no specific commitments regarding the collection, storage, " +
      "retention, or use of data submitted to or generated by this service. " +
      "Do not submit sensitive personal information, confidential material, " +
      "or anything you would not want processed by a third-party AI system.",
    ],
  },
  {
    heading: "Acceptable Use",
    paragraphs: ["You agree not to use Bark to:"],
    bullets: [
      "Violate any CMU policy or applicable law",
      "Attempt to disrupt, exploit, or gain unauthorized access to the service",
      "Submit harmful, abusive, or illegal content",
    ],
  },
  {
    heading: "Limitation of Liability",
    paragraphs: [
      "To the maximum extent permitted by law, ScottyLabs and its members " +
      "are not liable for any damages, losses, or issues arising from use " +
      "of Bark.",
    ],
  },
  {
    heading: "Changes",
    paragraphs: [
      "These terms may be updated at any time without prior notice. " +
      "Continued use of Bark constitutes acceptance of the current terms.",
    ],
  },
];

function TermsSection({ section }: { section: TermsSectionData }) {
  return (
    <section className="mt-6">
      <h2 className="text-base font-semibold text-neutral-900">
        {section.heading}
      </h2>
      {section.paragraphs.map((text) => (
        <p key={text} className="mt-2 text-sm leading-relaxed text-neutral-700">
          {text}
        </p>
      ))}
      {section.bullets !== undefined && (
        <ul className="mt-2 list-disc space-y-1 pl-6">
          {section.bullets.map((item) => (
            <li key={item} className="text-sm leading-relaxed text-neutral-700">
              {item}
            </li>
          ))}
        </ul>
      )}
      {section.trailing?.map((text) => (
        <p key={text} className="mt-2 text-sm leading-relaxed text-neutral-700">
          {text}
        </p>
      ))}
    </section>
  );
}

function TermsPage() {
  return (
    <div className="min-h-dvh bg-white">
      <main className="mx-auto w-full max-w-2xl px-6 py-10 sm:py-14">
        <Link
          to="/"
          search={{ chat: undefined, newChat: false }}
          className="text-sm font-medium text-neutral-500 hover:text-neutral-800"
        >
          &larr; Back to Bark
        </Link>
        <h1 className="mt-4 text-2xl font-bold text-neutral-900">
          Terms of Use &mdash; Bark
        </h1>
        <p className="mt-1 text-sm text-neutral-500">
          Last updated: {LAST_UPDATED}
        </p>
        {SECTIONS.map((section) => (
          <TermsSection key={section.heading} section={section} />
        ))}
        <section className="mt-6">
          <h2 className="text-base font-semibold text-neutral-900">Contact</h2>
          <p className="mt-2 text-sm leading-relaxed text-neutral-700">
            Questions or concerns:{" "}
            <a
              href="mailto:ops@scottylabs.org"
              className="underline hover:text-neutral-900"
            >
              ops@scottylabs.org
            </a>
          </p>
        </section>
      </main>
    </div>
  );
}
